Creando el readme
lee-fcsh/Orem pull request #3
Opened 2022-05-31 18:35 UTC by tati-18

Porfavor revisar el readme del repositorio Orem

2022-05-31 23:30 UTC, alealcor requested changes
Hacer el cambio del archivo y solicitar una nueva Review!

2022-05-31 23:30 UTC, alealcor commented on READFME.md.txt
> +_This project is a version for experiments of the "Laboratorio de Economía Experimental y del Comportamiento (LEE)" :card_index_dividers:_
El archivo tiene un nombre incorrecto. Esta como `READFME.md.txt` cuando solo deberia llamarse `README.md`

2022-06-02 03:20 UTC, tati-18 commented
Cambiando extension del readme

2022-06-02 14:12 UTC, alealcor approved these changes
Good job!! @tati-18

2022-06-02 23:28 UTC, merged