Action: Pylint #6
lee-fcsh/Orem pull request #7
Opened 2022-06-08 04:43 UTC by tati-18

Correcion de errores con Pylint

2022-06-08 15:08 UTC, alealcor commented
Problemas con el merge! @tati-18

2022-06-09 18:19 UTC, alealcor requested changes
Par de cambios a documentación

2022-06-09 18:19 UTC, alealcor commented on public_goods_simple/__init__.py
> +DOC = 'Description'
Añade una mejor descripción del proyecto

2022-06-09 18:19 UTC, alealcor commented on public_goods_simple/__init__.py
> +    """Function et_payoffss python version."""
Las definiciones de funciones se las trabaja con el formato que les subí la foto. Donde debes especificar args, returns y una breve descripción. 

Revisa la imagen en grande del issue #8

2022-06-09 18:19 UTC, alealcor commented on settings.py
> +"""Module environ."""
Una mejor explicación de lo que trata el archivo.

2022-06-09 18:19 UTC, alealcor commented on survey/__init__.py
> +DOC = "DESCRIPTION"
Mejor descripción

2022-06-09 18:19 UTC, alealcor commented on trust/__init__.py
> +"""Module ntpath python version."""
Same here

2022-06-09 18:19 UTC, alealcor commented on trust/__init__.py
> +DOC = """Simple trust game"""
Same here

2022-06-09 18:19 UTC, alealcor commented on trust/__init__.py
> +    """Function sent_back_amount_choices python version."""
Lo mismo con las funciones

2022-06-09 18:19 UTC, alealcor commented on trust/__init__.py
>  def set_payoffs(group: Group):
Tambien aki

2022-06-10 15:51 UTC, alealcor approved these changes
LGTM!!! Buen trabajo @tati-18

2022-06-10 15:52 UTC, alealcor commented
@tati-18 por favor, no te olvides de marcar como **Resolve conversation** cuando realices los cambios solicitados.

2022-06-13 21:51 UTC, merged

2022-06-13 21:55 UTC, tati-18 commented
Pull Resquest is resolve